### ISSUE TITLE
When a Computed function has a cached value it gets executed later when the cache is invalidated

### ISSUE THREAD

**Issue by garth** [cerebral/cerebral-computed#1]
1. On first render the computed function is run and the result is cached against the props/state
2. On second render with the same props/state the cached value from the previous execution is use and the computed function is not run (repeat this step many times)
3. On next render where the props/state have changed all Computed functions from 2. are executed (could be a lot).

**Comment by Guria** [comment]
Don't forget to move your issues to cerebral/cerebral#256 if any still actual.
